AI-Play/ML-Funcs

README.md
=> [DOCU] README updated

functions/README.md
=> functions directory added

main.py, requirements.txt
안경호
CORS로 인해 프론트-백 통신이 불가능한 상황 해결을 위한 코드 추가
None
프론트 측면에서의 상황 해결 과정을 알고 싶다면 Front-Web Repo의 Discussion 참고.
=> [BUG] CORS setting added

functions/__init__.py, functions/processing.py, main.py
---
이경희
merge와 concat 기능
함수: set_merge
API: /file/merge
```python
pandas.DataFrame.merge(pandas.DataFrame) # 의 결과를 리턴하는 함수
```
Args:
```
item        (Request, required): JSON
*
how         (str,     optional): Default "inner", inner: inner join, outer: outer join
on          (str,     optional): Default None,    조인할 대상 컬럼(양쪽 DataFrame에 다 있어야 함)
left_on     (str,     optional): Default None,    조인할 대상 컬럼(왼쪽)
right_on    (str,     optional): Default None,    조인할 대상 컬럼(오른쪽)
left_index  (str, …
```
=> [FeatureMade] merge & concat

functions/AI_plot.py, functions/__init__.py, functions/data2json.py, functions/templates/plot_test.html, main.py
---
김민석
데이터에 대한 box plot을 띄운다.
인풋 : json으로 변환된 데이터 프레임, 목표 특징 명(여러개)  
아웃풋 : component(plot)을 통해 script와 div를 구해 이를 반환
use:
```
box_plot(item, cols="특징,특징,특징")
```
Arg:
```
async def box_plot(
item : Request,                                         #data
cols : Optional[str] = Query(None, max_length = 30),    #출력하고자하는 특징들(string)
tools : Optional[str] = Query("", max_length= 20),      #...
background_fill_color : Optional[str] = Query("#efefef", max_length= 16),
fill_color1 : …
```
=> "[FeatureMade] Box Plot" 

functions/__init__.py, functions/eda.py, functions/processing.py, main.py
---
이름
to_json() => to_json(orient="records")
X
X
closes #47
=> to_json 수정

functions/data2json.py
---
이경희
to_json() => to_json(orient="records")
X
X
=> [버그 수정]20220221 to_json

functions/__init__.py, main.py
---
이경희
main.py import 버그 수정
X
X
=> [버그 수정] 20220221 main.py

functions/__init__.py, functions/eda.py, functions/processing.py
---
이경희
loc, iloc, col/condition
```python
df = pandas.DataFrame()
if   idx is None and col is None: df.loc[idx_from:idx_to, col_from:col_to]
elif idx is None                : df.loc[idx_from:idx_to, col]
elif col is None                : df.loc[idx, col_from:col_to]
else                            : df.loc[idx, col]
```
Args:
```
item     (Request, required): JSON
*
idx      (str,     optional): Default: None, 인덱스 명
idx_from (str,     optional): Default: None, 시작 인덱스 명
idx_to   (str, …
```
=> [FeatureMade] 20220222 loc, iloc, col/condition 이경희

functions/__init__.py, functions/eda.py, functions/processing.py, main.py
---
이경희
groupby, col_condition, unique  URL에 변수 삭제
X
X
closes #53
=> [FeadtureEdit] 20220222 groupby, col_condition, unique 수정

functions/eda.py, functions/preprocessing.py, functions/processing.py
---
이경희
```
item은 입력받을 dataframe,
col은 새로 생성 또는 값을 변경할 컬럼 명.(기존 컬럼에 있으면 기존 컬럼을 변경하고 아니면 새로 생성)
사용 방법 2가지
1. cols or col_from:col_to / func
2. cols_ops
둘 다 동시에 사용할 수 없음
※ func 사용시 유의사항
1. cols 를 사용하면 col_from:col_to 는 사용할 수 없습니다. 둘 중 하나 사용 가능
2. func는 다음 중 하나여야 합니다. ["sum", "count", "mean", "min", "max", "std", "median", "size"]
※ cols_ops 사용시 유의사항
1. column 명이 숫자일 경우, 컬럼을 연산하라는 것인지 숫자를 연산하라는 것인지 구분이 불가능합니다.
(키워드 약속하면 구분해서 처리할 수는 있습니다.)
2. + => %2b 로 파라미터를 보내셔야합니다
3. 반드시 column 또는 숫자로 시작해서 …
```
=> [FeatureMade] 20220223 컬럼 추가 및 변경 이경희

functions/eda.py
---
이경희
get_na, get_corr 에러 수정 및 corr percentiles 에러메시지 반환 추가
100 > percentiles >= 1 --> 100으로 나눠서 퍼센트로 인식
100 =< percentiles or 0>= percentiles --> 에러 메시지 반환
closes #59 
closes #60
=> 20220223 get_na, get_corr 수정

main.py, visualization/AI_plot.py
안경호
- 기존에 계획했던 div, script return 방식에 문제가 발생하여 json dump 방식으로 시각화 차트 데이터를 return 하게 수정하였습니다.
- 시각화 함수의 통신 방식을 get에서 post로 변경하였습니다.
- Bokeh figure의 파라미터 중 tools에 기본값이 들어가도록 수정하였습니다.
tools 외 기존과 동일
=> [BUG/FeatureMade] 시각화 관련 함수의 return 방식 등 수정

functions/__init__.py, functions/eda.py, functions/preprocessing.py, functions/processing.py, main.py
---
이경희
groupby, set_colulms size 제거, train_valid_split 추가
closes #69 
closes #70
=> [버그 수정] 20220228 groupby, set_colulms size 제거, train_valid_split 추가

functions/__init__.py, functions/eda.py, functions/preprocessing.py, functions/processing.py, main.py
---
김민석
결측치 존재시 에러메세지 반환을 하며 기존의 에러메세지를 문자열로 수정했습니다.
=> [FeatureMade] 결측치 & 에러메세지

functions/internal_func.py, functions/preprocessing.py
---
이경희
train_test_split 버그 수정
closes #80
=> [BUG FIX]20220313 train_test_split 버그 수정

main.py, visualization/AI_plot.py
안경호
시각화 기능의 HTTP Method가 get이었던 것을 post로 변경하였습니다.
기존에 post로 했었던 것 같은데 어쩌다가 get으로 바뀐 것인지 잘 모르겠습니다.
데이터프레임을 보내줘야 하기 때문에 POST 방식으로 해야 합니다.
(GET 방식은 body를 담을 수 없음)
=> [BUG] main.py visualization method get->post

functions/internal_func.py
---
이경희
ML-Func/functions/
위 경로에 아래와 같은 .env 파일을 생성 후 사용 가능
```
{
"host": "localhost",
"dbname": "postgres",
"user": "postgres",
"password": "aiplay",
"port": 5432
}
```
=> [FeatureMade] postgres func_log 저장 기능 20220320

config.py, functions/internal_func.py
안경호
기존 .env 세팅을 환경 변수 사용 방식으로 변경
=> [FeatureMade] .env setting updated

main.py
안경호
CORS Origins updated : 프론트앤드의 도메인 추가
=> [FeatureMade] CORS Origins updated

functions/eda.py
=> columns return code updated
